// Writes contracts/test/fixtures/webcrypto.json from the SDK itself; contracts/test/Fixtures.t.sol checks it.
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname } from "node:path";
import { fileURLToPath } from "node:url";
import { base64url, type JWK } from "jose";
import { bytesToHex, sha256, toHex, type Address } from "viem";
import {
  anchorMessage,
  buildBatch,
  buildReceipt,
  commitRequest,
  commitResponse,
  createHostSigner,
  leafHash,
  newSalt,
  normalizeS,
  receiptHash,
  splitRawSignature,
} from "../src/index.js";

const OUT = fileURLToPath(new URL("../../contracts/test/fixtures/webcrypto.json", import.meta.url));

// Must match the constants in Fixtures.t.sol.
const CHAIN_ID = 31337n;
const ANCHOR_ADDRESS: Address = "0x00000000000000000000000000000000a55a7000";
const AGENT_ID = 1n;

const pair = await crypto.subtle.generateKey({ name: "ECDSA", namedCurve: "P-256" }, true, ["sign"]);
const privateJwk = (await crypto.subtle.exportKey("jwk", pair.privateKey)) as JWK;
const host = await createHostSigner(privateJwk, "fixture-key");
const key = { x: bytesToHex(base64url.decode(host.publicJwk.x!)), y: bytesToHex(base64url.decode(host.publicJwk.y!)) };

const signatures = [];
for (let i = 0; i < 10; i++) {
  const message = crypto.getRandomValues(new Uint8Array(32));
  const raw = new Uint8Array(await crypto.subtle.sign({ name: "ECDSA", hash: "SHA-256" }, pair.privateKey, message));
  signatures.push({ message: toHex(message), digest: sha256(message), ...normalizeS(splitRawSignature(raw)) });
}

const receipts = Array.from({ length: 8 }, (_, i) => {
  const salt = newSalt();
  const body = buildReceipt({
    model: "z-ai/glm-5.3",
    host: { agentId: `erc8004:10143:${AGENT_ID}`, keyId: "fixture-key", alg: "ES256" },
    req: {
      commit: commitRequest(salt, [{ role: "user", content: `question ${i}` }], { max_tokens: 16 }),
      params: { max_tokens: 16 },
    },
    res: { commit: commitResponse(salt, `answer ${i}`), tokensIn: 10 + i, tokensOut: 3, finish: "stop" },
  });
  return receiptHash(body);
});
const batch = buildBatch(receipts);
const anchor = { chainId: CHAIN_ID, anchor: ANCHOR_ADDRESS, agentId: AGENT_ID, root: batch.root, count: receipts.length };
const anchorSig = await host.signAnchor(anchor);

const fixture = {
  note: "Generated by sdk/scripts/gen-vectors.ts from the SDK. digest = sha256(message); s is normalized to low-s.",
  key,
  signatures,
  highSCount: signatures.filter((s) => s.wasHighS).length,
  anchor: {
    chainId: Number(CHAIN_ID),
    address: ANCHOR_ADDRESS,
    agentId: Number(AGENT_ID),
    count: receipts.length,
    message: anchorMessage(anchor),
    r: anchorSig.r,
    s: anchorSig.s,
  },
  merkle: { root: batch.root, receipts, leaves: receipts.map(leafHash), proofs: receipts.map((h) => batch.proofs.get(h)) },
};

mkdirSync(dirname(OUT), { recursive: true });
writeFileSync(OUT, JSON.stringify(fixture, null, 2) + "\n");
console.log(`wrote ${OUT}: ${signatures.length} signatures (${fixture.highSCount} were high-s), 8 SDK receipts, 1 anchor`);
